title: Prospekte
description: >-
  Bdasdasda
baseurl: ""
url: "https://vwlinks.kicktemp.com"

# Build settings
markdown: kramdown

#Exclude Files or Folder
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, bower_components, bower.json, Gemfile, Gemfile.lock, CNAME, .idea, .git]

repository: kicktemp/vwlinks
